CREATE TABLE [dbo].[Address] (
	[Title] AS CONCAT([City], ' ', [Street], ' ', [House]),
	[Country] NVARCHAR(255) NULL,
	[PostalCode] NVARCHAR(255) NULL,
	[Locality] NVARCHAR(255) NULL,
	[Region] NVARCHAR(255) NULL,
	[City] NVARCHAR(255) NULL,
	[Town] NVARCHAR(255) NULL,
	[Street] NVARCHAR(255) NULL,
	[House] NVARCHAR(255) NULL,
	[Building] NVARCHAR(255) NULL,
	[Structure] NVARCHAR(255) NULL,
	[Facility] NVARCHAR(255) NULL,
	[Ownership] NVARCHAR(255) NULL,
	[Flat] NVARCHAR(255) NULL,
	[POBox] NVARCHAR(255) NULL,
	[Okato] NVARCHAR(255) NULL,
	[KladrCode] NVARCHAR(255) NULL,
	[KladrStreetCode] NVARCHAR(255) NULL,
	[OMKDistrictCode] NVARCHAR(255) NULL,
	[OMKRegionCode] NVARCHAR(255) NULL,
	[OMKTownCode] NVARCHAR(255) NULL,
	[OMKStreetCode] NVARCHAR(255) NULL,
	[BTIStreetCode] NVARCHAR(255) NULL,
	[BTIBuildingCode] NVARCHAR(255) NULL,
	[Type] NVARCHAR(255) NULL,
	[Id] INT NOT NULL PRIMARY KEY IDENTITY (1, 1),
	[MessageId] VARCHAR(36) NOT NULL,
	CONSTRAINT [CK_Address_Type] CHECK (([Type] IN ('RegAddress', 'FactAddress', 'BirthAddress', 'PostalAddress')))
	);