CREATE TABLE [dbo].[DEBUG_DATA]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	[DATE] DATETIME,
	[DATA_STR1] NVARCHAR(MAX),
	[DATA_STR2] NVARCHAR(MAX),
	[DATA_STR3] NVARCHAR(MAX),
	[DATA_STR4] NVARCHAR(MAX),
	[DATA_STR5] NVARCHAR(MAX),
	[DATA_INT1] INT,
	[DATA_INT2] INT,
	[DATA_INT3] INT,
	[DATA_INT4] INT,
	[DATA_INT5] INT,
)
