CREATE TABLE [dbo].[GibddPenaltyV5]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	[BreachDateTime] DATETIME,
	[BreachPlace] NVARCHAR(512),
	[DateSSP] DATETIME,
	[DecisionDate] DATETIME,
	[DecisionNumber] NVARCHAR(255),
	[DecisionSumma] NVARCHAR(128),
	[DecisionTerm] NVARCHAR(128),
	[DepartmentDecided]	NVARCHAR(128),
	[DocNumber]	NVARCHAR(128),
	[DocType] NVARCHAR(128),
	[DriveLicenseEndDate] DATETIME,
	[DriveLicenseOutDate] DATETIME,
	[EndDate] DATETIME,
	[ExecDepartment] NVARCHAR(128),
	[ExecutionState] NVARCHAR(255),
	[KOAPText] NVARCHAR(128),
	[LicenseStartDate] DATETIME,
	[LicenseWithdrawalDate]	DATETIME,
	[Penalty] NVARCHAR(128),
	[PostNum] NVARCHAR(128),
	[RWaitDate]	DATETIME,
	[RegionWhere] NVARCHAR(128),
	[RequestID] NVARCHAR(128),
	[StateName]	NVARCHAR(1024),
	[SupplierBillID] NVARCHAR(128),
	[UnicNumber] NVARCHAR(128) NOT NULL,
	[VehicleCategory] NVARCHAR(128),
	[VehicleModel] NVARCHAR(128),
	[VehicleOwnerCategory] NVARCHAR(128),
	[VehicleRegPoint] NVARCHAR(32),
	[WaitDate] DATETIME,
	[WhoDecided] NVARCHAR(128),
	[roskaznaIn] NVARCHAR(32),
	CONSTRAINT UQ_GibddPenaltyV5_UnicNumber UNIQUE([UnicNumber]) WITH (IGNORE_DUP_KEY = ON)
)
