CREATE TABLE [dbo].[License]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	[Title] as [RegNumber],
    [RegNumber] NVARCHAR(64) NULL, 
    [BlankSeries] NVARCHAR(12) NULL, 
    [BlankNo] NVARCHAR(12) NULL, 
    [OrgName] NVARCHAR(255) NULL, 
    [Ogrn] NVARCHAR(255) NULL, 
    [Inn] NVARCHAR(255) NULL, 
    [Parent] INT NULL, 
	[RootParent] INT NULL, 
    [Status] INT NULL, 
    [Document] XML NULL, 
    [Signature] XML NULL, 
    [TaxiId] INT NULL, 
    [Lfb] NVARCHAR(128) NULL, 
    [JuridicalAddress] NVARCHAR(255) NULL, 
    [PhoneNumber] NVARCHAR(64) NULL, 
    [AddContactData] NVARCHAR(MAX) NULL, 
    [AccountAbbr] NVARCHAR(12) NULL, 
    [TaxiBrand] NVARCHAR(64) NULL, 
    [TaxiModel] NVARCHAR(64) NULL, 
    [TaxiStateNumber] NVARCHAR(24) NULL, 
    [TaxiYear] INT NULL, 
    [OutputDate] DATETIME NULL, 
    [CreationDate] DATETIME NULL, 
    [TillDate] DATETIME NULL, 
    [TillSuspensionDate] DATETIME NULL, 
    [CancellationReason] NVARCHAR(MAX) NULL, 
    [SuspensionReason] NVARCHAR(MAX) NULL, 
    [ChangeReason] NVARCHAR(MAX) NULL, 
    [InvalidReason] NVARCHAR(MAX) NULL,  
    CONSTRAINT [FK_License_ToLicense_Parent] FOREIGN KEY ([Parent]) REFERENCES [dbo].[License]([Id]),
	CONSTRAINT [FK_License_ToLicense_RootParent] FOREIGN KEY ([RootParent]) REFERENCES [dbo].[License]([Id]) 
)
