CREATE TABLE [dbo].[RequestContact] (
	[Id] NVARCHAR(255) NULL,
	[Title] AS CONCAT([LastName], ' ', [FirstName], ' ', [MiddleName]),
	[LastName] NVARCHAR(255) NULL,
	[FirstName] NVARCHAR(255) NULL,
	[MiddleName] NVARCHAR(255) NULL,
	[Gender] NVARCHAR(255) NULL,
	[BirthDate] DATETIME NULL,
	[Snils] NVARCHAR(255) NULL,
	[Inn] NVARCHAR(255) NULL,
	[MobilePhone] NVARCHAR(255) NULL,
	[WorkPhone] NVARCHAR(255) NULL,
	[HomePhone] NVARCHAR(255) NULL,
	[EMail] NVARCHAR(255) NULL,
	[Nation] NVARCHAR(255) NULL,
	[Citizenship] NVARCHAR(255) NULL,
	[CitizenshipType] NVARCHAR(255) NULL,
	[JobTitle] NVARCHAR(255) NULL,
	[OMSNum] NVARCHAR(255) NULL,
	[OMSDate] DATETIME NULL,
	[OMSCompany] NVARCHAR(255) NULL,
	[OMSValidityPeriod] NVARCHAR(255) NULL,
	[IsiId] NVARCHAR(255) NULL,
	[Id_Auto] INT NOT NULL PRIMARY KEY IDENTITY (1, 1),
	[MessageId] VARCHAR(36) NOT NULL,
	[RegAddress] INT NULL,
	[FactAddress] INT NULL,
	[BirthAddress] INT NULL,
	[SingleStrRegAddress] AS ([dbo].[fn_BuildAddressSingleString](RegAddress)),
	[SingleStrFactAddress] AS ([dbo].[fn_BuildAddressSingleString](FactAddress)),
	[SingleStrBirthAddress] AS ([dbo].[fn_BuildAddressSingleString](BirthAddress)),
	CONSTRAINT [FK_RequestContact_RegAddress] FOREIGN KEY ([RegAddress]) REFERENCES [dbo].[Address]([Id]),
	CONSTRAINT [FK_RequestContact_FactAddress] FOREIGN KEY ([FactAddress]) REFERENCES [dbo].[Address]([Id]),
	CONSTRAINT [FK_RequestContact_BirthAddress] FOREIGN KEY ([BirthAddress]) REFERENCES [dbo].[Address]([Id])
	);