CREATE TABLE [dbo].[taxi_info] (
	[blankno] NVARCHAR(255) NULL,
	[brand] NVARCHAR(255) NULL,
	[brandname] NVARCHAR(255) NULL,
	[checked] BIT NULL,
	[color] NVARCHAR(255) NULL,
	[color_2] NVARCHAR(255) NULL,
	[color_number] BIT NULL,
	[color_yellow] BIT NULL,
	[condition] INT NULL,
	CONSTRAINT [CK_taxi_info_condition] CHECK (([condition] IN (1, 3, 4, 6, 2, 5, 7))),
	[date_ran] NVARCHAR(255) NULL,
	[decision] BIT NULL,
	[declinereason] NVARCHAR(255) NULL,
	[details] NVARCHAR(255) NULL,
	[doc] INT NULL,
	CONSTRAINT [CK_taxi_info_doc] CHECK (([doc] IN (1, 2, 3, 4))),
	[gps] BIT NULL,
	[licensedate] NVARCHAR(255) NULL,
	[licensenum] NVARCHAR(255) NULL,
	[lizdetails] NVARCHAR(255) NULL,
	[model] NVARCHAR(255) NULL,
	[name] NVARCHAR(255) NULL,
	[num] NVARCHAR(255) NULL,
	[num2] NVARCHAR(255) NULL,
	[number_ran] NVARCHAR(255) NULL,
	[owner] NVARCHAR(255) NULL,
	[taxi_info_old] NVARCHAR(255) NULL,
	[taxometr] BIT NULL,
	[todate] DATETIME NULL,
	[year] INT NULL,
	[Id] INT NOT NULL IDENTITY (1, 1),
	[MessageId] VARCHAR(36) NOT NULL,
	[ServiceProperties] INT NOT NULL
	);