// <copyright file="UtilityEntities.cs" company="Armd">
// Copyright Armd. All rights reserved.
// </copyright>
// <author>SPDOMAIN\dev1</author>
// <date>2014-10-28 12:11:32Z</date>
// <auto-generated>
//   Generated with SharePoint Software Factory 4.1
// </auto-generated>
namespace TM.SP.BCSModels.Utility
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

    /// <summary>
    /// This class contains the properties for RequestCounter
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("SPSF", "4.1")]
    public partial class RequestCounter
    {
        //TODO: Implement additional properties here.
        public System.Int32 Id { get; set; }
        public System.Int32 Title { get; set; }
        public System.Int32 Year { get; set; }
        public System.String ServiceCode { get; set; }
        public System.Int32 CounterValue { get; set; }
    }
}

