// <copyright file="TaxiEntities.cs" company="Armd">
// Copyright Armd. All rights reserved.
// </copyright>
// <author>SPDEV\developer</author>
// <date>2014-09-30 12:37:24Z</date>
// <auto-generated>
//   Generated with SharePoint Software Factory 4.1
// </auto-generated>

using System.CodeDom.Compiler;

namespace TM.SP.BCSModels.Taxi
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Xml.Serialization;

    /// <summary>
    /// This class contains the properties for License
    /// </summary>
    [GeneratedCode("SPSF", "4.1")]
    [Serializable]
    public partial class License
    {
        #region [properties]
        [XmlIgnore]
        public Int32 Id { get; set; }
        [XmlIgnore]
        public String Title { get; set; }
        public String RegNumber { get; set; }
        public String BlankSeries { get; set; }
        public String BlankNo { get; set; }
        public String OrgName { get; set; }
        public String Ogrn { get; set; }
        public String Inn { get; set; }
        [XmlIgnore]
        public int? Parent { get; set; }
        [XmlIgnore]
        public int? RootParent { get; set; }
        public int? Status { get; set; }
        [XmlIgnore]
        public String Document { get; set; }
        [XmlIgnore]
        public String Signature { get; set; }
        [XmlIgnore]
        public int? TaxiId { get; set; }
        public String Lfb { get; set; }
        public String JuridicalAddress { get; set; }
        public String PhoneNumber { get; set; }
        public String AddContactData { get; set; }
        public String AccountAbbr { get; set; }
        public String TaxiBrand { get; set; }
        public String TaxiModel { get; set; }
        public String TaxiStateNumber { get; set; }
        public int? TaxiYear { get; set; }
        public DateTime? OutputDate { get; set; }
        public DateTime? CreationDate { get; set; }
        public DateTime? TillDate { get; set; }
        public DateTime? TillSuspensionDate { get; set; }
        public String CancellationReason { get; set; }
        public String SuspensionReason { get; set; }
        public String ChangeReason { get; set; }
        public String InvalidReason { get; set; }
        public String ShortName { get; set; }
        public String LastName { get; set; }
        public String FirstName { get; set; }
        public String SecondName { get; set; }
        public DateTime? OgrnDate { get; set; }
        public String Country { get; set; }
        public String PostalCode { get; set; }
        public String Locality { get; set; }
        public String Region { get; set; }
        public String City { get; set; }
        public String Town { get; set; }
        public String Street { get; set; }
        public String House { get; set; }
        public String Building { get; set; }
        public String Structure { get; set; }
        public String Facility { get; set; }
        public String Ownership { get; set; }
        public String Flat { get; set; }
        public String Fax { get; set; }
        public String EMail { get; set; }
        public String TaxiColor { get; set; }
        public String TaxiNumberColor { get; set; }
        public String TaxiVin { get; set; }
        public DateTime? ChangeDate { get; set; }
        [XmlIgnore]
        public String Guid_OD { get; set; }
        [XmlIgnore]
        public DateTime? Date_OD { get; set; }
        [XmlIgnore]
        public bool? FromPortal { get; set; }
        public System.String FirmName { get; set; }
        public System.String Brand { get; set; }
        public System.String OgrnNum { get; set; }
        public System.String OgrnName { get; set; }
        public System.String GRAddress { get; set; }
        public DateTime? InnDate { get; set; }
        public System.String InnName { get; set; }
        public System.String InnNum { get; set; }
        public System.String Address_Fact { get; set; }
        public System.String Country_Fact { get; set; }
        public System.String PostalCode_Fact { get; set; }
        public System.String Locality_Fact { get; set; }
        public System.String Region_Fact { get; set; }
        public System.String City_Fact { get; set; }
        public System.String Town_Fact { get; set; }
        public System.String Street_Fact { get; set; }
        public System.String House_Fact { get; set; }
        public System.String Building_Fact { get; set; }
        public System.String Structure_Fact { get; set; }
        public System.String Facility_Fact { get; set; }
        public System.String Ownership_Fact { get; set; }
        public System.String Flat_Fact { get; set; }
        public bool? Gps { get; set; }
        public bool? Taxometr { get; set; }
        public DateTime? TODate { get; set; }
        public System.String STSNumber { get; set; }
        public DateTime? STSDate { get; set; }
        public int? OwnType { get; set; }
        public System.String OwnNumber { get; set; }
        public DateTime? OwnDate { get; set; }
        public bool? MO { get; set; }
        public System.String GUID_MO { get; set; }
        public DateTime? DATE_MO { get; set; }
        [XmlIgnore]
        public bool? Obsolete { get; set; }
        [XmlIgnore]
        public bool? DisableGibddSend { get; set; }
        #endregion

        #region [methods]

        public License Clone() 
        {
            return new License()
            {
                AccountAbbr        = AccountAbbr,
                AddContactData     = AddContactData,
                BlankNo            = BlankNo,
                BlankSeries        = BlankSeries,
                CancellationReason = CancellationReason,
                ChangeReason       = ChangeReason,
                CreationDate       = DateTime.Now,
                Document           = String.Empty,
                Id                 = 0,
                Inn                = Inn,
                InvalidReason      = InvalidReason,
                JuridicalAddress   = JuridicalAddress,
                Lfb                = Lfb,
                Ogrn               = Ogrn,
                OrgName            = OrgName,
                OutputDate         = OutputDate,
                Parent             = Id,
                RootParent         = RootParent ?? Id,
                PhoneNumber        = PhoneNumber,
                RegNumber          = RegNumber,
                Signature          = String.Empty,
                Status             = Status,
                SuspensionReason   = SuspensionReason,
                TaxiBrand          = TaxiBrand,
                TaxiId             = TaxiId,
                TaxiModel          = TaxiModel,
                TaxiStateNumber    = TaxiStateNumber,
                TaxiYear           = TaxiYear,
                TillDate           = TillDate,
                TillSuspensionDate = TillSuspensionDate,
                ShortName          = ShortName,
                LastName           = LastName,
                FirstName          = FirstName,
                SecondName         = SecondName,
                OgrnDate           = OgrnDate,
                Country            = Country,
                PostalCode         = PostalCode,
                Locality           = Locality,
                Region             = Region,
                City               = City,
                Town               = Town,
                Street             = Street,
                House              = House,
                Building           = Building,
                Structure          = Structure,
                Facility           = Facility,
                Ownership          = Ownership,
                Flat               = Flat,
                Fax                = Fax,
                EMail              = EMail,
                TaxiColor          = TaxiColor
                ,TaxiNumberColor   = TaxiNumberColor,
                TaxiVin            = TaxiVin,
                ChangeDate         = DateTime.Now,
                Guid_OD            = Guid_OD,
                Date_OD            = null,
                FromPortal         = FromPortal,
                FirmName           = FirmName,
                Brand              = Brand,
                OgrnNum            = OgrnNum,
                OgrnName           = OgrnName,
                GRAddress          = GRAddress,
                InnDate            = InnDate,
                InnName            = InnName,
                InnNum             = InnNum,
                Address_Fact       = Address_Fact,
                Country_Fact       = Country_Fact,
                PostalCode_Fact    = PostalCode_Fact,
                Locality_Fact      = Locality_Fact,
                Region_Fact        = Region_Fact,
                City_Fact          = City_Fact,
                Town_Fact          = Town_Fact,
                Street_Fact        = Street_Fact,
                House_Fact         = House_Fact,
                Building_Fact      = Building_Fact,
                Structure_Fact     = Structure_Fact,
                Facility_Fact      = Facility_Fact,
                Ownership_Fact     = Ownership_Fact,
                Flat_Fact          = Flat_Fact,
                Gps                = Gps,
                Taxometr           = Taxometr,
                TODate             = TODate,
                STSNumber          = STSNumber,
                STSDate            = STSDate,
                OwnType            = OwnType,
                OwnNumber          = OwnNumber,
                OwnDate            = OwnDate,
                MO                 = MO,
                GUID_MO            = GUID_MO,
                DATE_MO            = null,
                Obsolete           = Obsolete,
                DisableGibddSend   = DisableGibddSend
            };
        }

        #endregion
    }
}

