// <copyright file="TaxiEntityServices.cs" company="Armd">
// Copyright Armd. All rights reserved.
// </copyright>
// <author>SPDEV\developer</author>
// <date>2014-09-30 12:37:24Z</date>
// <auto-generated>
//   Generated with SharePoint Software Factory 4.1
// </auto-generated>
namespace TM.SP.BCSModels.Taxi
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Data;
    using System.Data.Sql;
    using System.Data.SqlClient;
    using System.Data.SqlTypes;
    using System.Runtime.InteropServices;
    using Microsoft.BusinessData;
    using Microsoft.BusinessData.SystemSpecific;

    using Utils;
    using Helpers;

    // Base class to share connection string retrieval for all entities
    [System.CodeDom.Compiler.GeneratedCode("SPSF", "4.1")]
    public class TaxiService : IContextProperty
    {
        public Microsoft.BusinessData.Runtime.IExecutionContext ExecutionContext
        {
            get;
            set;
        }

        public Microsoft.BusinessData.MetadataModel.ILobSystemInstance LobSystemInstance
        {
            get;
            set;
        }

        public Microsoft.BusinessData.MetadataModel.IMethodInstance MethodInstance
        {
            get;
            set;
        }

        protected SqlConnection getSqlConnection()
        {
            var secureStoreAppId = BCS.GetLobSystemProperty(LobSystemInstance, "SecureStoreAppId");

            var cBuilder = new SqlConnectionStringBuilder()
            {
                DataSource     = BCS.GetLobSystemProperty(LobSystemInstance, "DBServerName"),
                InitialCatalog = BCS.GetLobSystemProperty(LobSystemInstance, "DBName"),
                UserID         = Security.GetSecureStoreUserNameCredential(secureStoreAppId),
                Password       = Security.GetSecureStorePasswordCredential(secureStoreAppId)
            };

            return new SqlConnection(cBuilder.ConnectionString);
        }
    }

    /// <summary>
    /// All the methods for retrieving, updating and deleting data are implemented in this class file.
    /// The samples below show the finder and specific finder method for Entity1.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("SPSF", "4.1")]
    public partial class LicenseEntityService : TaxiService
    {
        public License ReadLicenseItem(Int32 id)
        {
            License entity = null;

            entity = new License();
            SqlConnection thisConn = getSqlConnection();
            thisConn.Open();
            var selectCommand = new SqlCommand
            {
                CommandText = SqlHelper.LoadSQLStatement("License-ReadItem.sql")
                    
            };
            selectCommand.Parameters.AddWithValue("@Id", id);

            selectCommand.Connection = thisConn;
            SqlDataReader thisReader = selectCommand.ExecuteReader(CommandBehavior.CloseConnection);
            if (thisReader.Read())
            {
                SqlHelper.LicenseFillFromReader(entity, thisReader);
            }
            else
            {
                throw new Exception("Data not found");
            }
            thisReader.Close();
            return (entity);
        }
        public IList<License> ReadLicenseList()
        {
            SqlConnection thisConn = null;
            List<License> allEntities = new List<License>();

            thisConn = getSqlConnection();
            thisConn.Open();
            SqlCommand selectCommand = new SqlCommand();
            selectCommand.Connection = thisConn;
            selectCommand.CommandText = SqlHelper.LoadSQLStatement("License-ReadAllItems.sql");
            SqlDataReader thisReader = selectCommand.ExecuteReader(CommandBehavior.CloseConnection);
            while (thisReader.Read())
            {
                License entity = new License();
                SqlHelper.LicenseFillFromReader(entity, thisReader);
                allEntities.Add(entity);
            }
            thisReader.Close();
            return allEntities;
        }
        public License CreateLicense(License newentity)
        {
            License createdEntity = null;
            SqlConnection thisConn = null;
            try
            {
                thisConn = getSqlConnection();
                thisConn.Open();

                SqlCommand createCommand = new SqlCommand();
                createCommand.Connection = thisConn;
                createCommand.CommandText = SqlHelper.LoadSQLStatement("License-CreateItem.sql");
                SqlHelper.NewLicenseParams(newentity, createCommand.Parameters);

                SqlDataReader thisReader = createCommand.ExecuteReader(CommandBehavior.CloseConnection);
                if (thisReader.Read())
                {
                    createdEntity = new License();
                    SqlHelper.LicenseFillFromReader(createdEntity, thisReader);
                }
                else
                {
                    throw new Exception("Data not found");
                }
                return createdEntity;
            }
            finally
            {
                thisConn.Dispose();
            }
        }
        public void DeleteLicense(System.Int32 Id)
        {
            SqlConnection thisConn = null;
            try
            {
                thisConn = getSqlConnection();
                thisConn.Open();

                SqlCommand deleteCommand = new SqlCommand();
                deleteCommand.Connection = thisConn;
                deleteCommand.CommandText = SqlHelper.LoadSQLStatement("License-DeletItem.sql");
                deleteCommand.Parameters.AddWithValue("@Id", Id);
                deleteCommand.ExecuteNonQuery();
            }
            finally
            {
                thisConn.Dispose();
            }

        }
        public void UpdateLicense(License updateLicense)
        {
            SqlConnection thisConn = null;
            try
            {
                thisConn = getSqlConnection();
                thisConn.Open();

                SqlCommand updateCommand = new SqlCommand();
                updateCommand.Connection = thisConn;
                updateCommand.CommandText = SqlHelper.LoadSQLStatement("License-UpdateItem.sql");
                SqlHelper.UpdateLicenseParams(updateLicense, updateCommand.Parameters);

                updateCommand.ExecuteNonQuery();
            }
            finally
            {
                thisConn.Dispose();
            }
        }
        public IList<License> IdOfLicenseToParentOfLicense(System.Nullable<System.Int32> Parent)
        {
            SqlConnection thisConn = null;
            List<License> allEntities = new List<License>();

            thisConn = getSqlConnection();
            thisConn.Open();
            SqlCommand selectCommand = new SqlCommand();
            selectCommand.Connection = thisConn;
            selectCommand.CommandText = SqlHelper.LoadSQLStatement("License-ReadItemsByParent.sql");

            selectCommand.Parameters.AddWithValue("@Parent", Parent);

            SqlDataReader thisReader = selectCommand.ExecuteReader(CommandBehavior.CloseConnection);
            while (thisReader.Read())
            {
                License entity = new License();
                SqlHelper.LicenseFillFromReader(entity, thisReader);
                allEntities.Add(entity);
            }
            thisReader.Close();
            return allEntities;
        }
        public IList<License> IdOfLicenseToRootParentOfLicense(System.Nullable<System.Int32> RootParent)
        {
            SqlConnection thisConn = null;
            List<License> allEntities = new List<License>();

            thisConn = getSqlConnection();
            thisConn.Open();
            SqlCommand selectCommand = new SqlCommand();
            selectCommand.Connection = thisConn;
            selectCommand.CommandText = SqlHelper.LoadSQLStatement("License-ReadItemsByRootParent.sql");
            selectCommand.Parameters.AddWithValue("@RootParent", RootParent);

            SqlDataReader thisReader = selectCommand.ExecuteReader(CommandBehavior.CloseConnection);
            while (thisReader.Read())
            {
                License entity = new License();
                SqlHelper.LicenseFillFromReader(entity, thisReader);
                allEntities.Add(entity);
            }
            thisReader.Close();
            return allEntities;
        }
    }
}

