//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClientGIBDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppLog
    {
        public System.Guid ID { get; set; }
        public System.DateTime EventDateTime { get; set; }
        public string ApplicationName { get; set; }
        public string Direction { get; set; }
        public string Message { get; set; }
        public Nullable<System.Guid> MessageID { get; set; }
    }
}
