//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClientGIBDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExcludeVehicles
    {
        public System.Guid ID { get; set; }
        public string owner { get; set; }
        public string licenseId { get; set; }
        public string catalogNumber { get; set; }
        public string licencePlateNumber { get; set; }
        public Nullable<System.DateTime> uploadDate { get; set; }
        public Nullable<System.DateTime> cancelDate { get; set; }
        public string cancelComment { get; set; }
    }
}
