//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClientGIBDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialVehiclesRegister
    {
        public System.Guid ID { get; set; }
        public Nullable<int> License_id { get; set; }
        public Nullable<System.Guid> RecordId { get; set; }
        public string PackageId { get; set; }
        public string ProccessingStageCode { get; set; }
        public Nullable<System.DateTime> ProcessingStageDate { get; set; }
        public string ProcessingStageInfo { get; set; }
        public string RecordStatusCode { get; set; }
        public string RecordStatusText { get; set; }
        public string Exception { get; set; }
    
        public virtual License License { get; set; }
    }
}
