//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClientGIBDD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TmDataModelContainer : DbContext
    {
        public TmDataModelContainer()
            : base("name=TmDataModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ExcludeVehicles> ExcludeVehicles { get; set; }
        public DbSet<License> License { get; set; }
        public DbSet<SpecialVehiclesRegister> SpecialVehiclesRegister { get; set; }
        public DbSet<AppLog> AppLog { get; set; }
        public DbSet<GibddServiceErrors> GibddServiceErrors { get; set; }
    }
}
