//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.PlumsailFormsBackup {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringsRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SP.PlumsailFormsBackup.StringsRes", typeof(StringsRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Во время выполнения резервного копирования произошла ошибка. Подробности: {0}.
        /// </summary>
        internal static string BackupTimerCommonErrFmt {
            get {
                return ResourceManager.GetString("BackupTimerCommonErrFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlumsailFormsBackup.
        /// </summary>
        internal static string BackupTimerDefaultFolderName {
            get {
                return ResourceManager.GetString("BackupTimerDefaultFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fd_{0}_{1}_{2}.
        /// </summary>
        internal static string BackupTimerFormNameFmt {
            get {
                return ResourceManager.GetString("BackupTimerFormNameFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каталог для хранения резервных копий не существует либо недоступен (каталог = {0}).
        /// </summary>
        internal static string BackupTimerInvalidPathErrFmt {
            get {
                return ResourceManager.GetString("BackupTimerInvalidPathErrFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указан каталог для хранения резервных копий.
        /// </summary>
        internal static string BackupTimerNullPathErr {
            get {
                return ResourceManager.GetString("BackupTimerNullPathErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Резервное копирование форм дизайнера Plumsail.
        /// </summary>
        internal static string BackupTimerTitle {
            get {
                return ResourceManager.GetString("BackupTimerTitle", resourceCulture);
            }
        }
    }
}
