//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18449
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClientGIBDD.ModerationJournalQueryService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:ws.query.moderationjournal", ConfigurationName="ModerationJournalQueryService.ModerationJournalQueryService")]
    public interface ModerationJournalQueryService {
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (queryCancelledLicensesRequest) сообщения getCancelledLicensesRequest не соответствует значению по умолчанию (getCancelledLicenses).
        [System.ServiceModel.OperationContractAttribute(Action="urn:getCancelledLicensesAction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebClientGIBDD.ModerationJournalQueryService.getCancelledLicensesResponse getCancelledLicenses(WebClientGIBDD.ModerationJournalQueryService.getCancelledLicensesRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ws.query.moderationjournal")]
    public partial class CancelledLicensesFilter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ownerField;
        
        private System.DateTime cancelStartDateField;
        
        private bool cancelStartDateFieldSpecified;
        
        private System.DateTime cancelEndDateField;
        
        private bool cancelEndDateFieldSpecified;
        
        private string licencePlateNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
                this.RaisePropertyChanged("owner");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime cancelStartDate {
            get {
                return this.cancelStartDateField;
            }
            set {
                this.cancelStartDateField = value;
                this.RaisePropertyChanged("cancelStartDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cancelStartDateSpecified {
            get {
                return this.cancelStartDateFieldSpecified;
            }
            set {
                this.cancelStartDateFieldSpecified = value;
                this.RaisePropertyChanged("cancelStartDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime cancelEndDate {
            get {
                return this.cancelEndDateField;
            }
            set {
                this.cancelEndDateField = value;
                this.RaisePropertyChanged("cancelEndDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cancelEndDateSpecified {
            get {
                return this.cancelEndDateFieldSpecified;
            }
            set {
                this.cancelEndDateFieldSpecified = value;
                this.RaisePropertyChanged("cancelEndDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=3)]
        public string licencePlateNumber {
            get {
                return this.licencePlateNumberField;
            }
            set {
                this.licencePlateNumberField = value;
                this.RaisePropertyChanged("licencePlateNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ws.query.moderationjournal")]
    public partial class ResponseLicense : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ownerField;
        
        private string licenseIdField;
        
        private string catalogNumberField;
        
        private string licencePlateNumberField;
        
        private System.DateTime uploadDateField;
        
        private System.DateTime cancelDateField;
        
        private string cancelCommentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
                this.RaisePropertyChanged("owner");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string licenseId {
            get {
                return this.licenseIdField;
            }
            set {
                this.licenseIdField = value;
                this.RaisePropertyChanged("licenseId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string catalogNumber {
            get {
                return this.catalogNumberField;
            }
            set {
                this.catalogNumberField = value;
                this.RaisePropertyChanged("catalogNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=3)]
        public string licencePlateNumber {
            get {
                return this.licencePlateNumberField;
            }
            set {
                this.licencePlateNumberField = value;
                this.RaisePropertyChanged("licencePlateNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime uploadDate {
            get {
                return this.uploadDateField;
            }
            set {
                this.uploadDateField = value;
                this.RaisePropertyChanged("uploadDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime cancelDate {
            get {
                return this.cancelDateField;
            }
            set {
                this.cancelDateField = value;
                this.RaisePropertyChanged("cancelDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string cancelComment {
            get {
                return this.cancelCommentField;
            }
            set {
                this.cancelCommentField = value;
                this.RaisePropertyChanged("cancelComment");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ws.query.moderationjournal")]
    public enum ResponseStatusType {
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        ERROR,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="queryCancelledLicensesRequest", WrapperNamespace="urn:ws.query.moderationjournal", IsWrapped=true)]
    public partial class getCancelledLicensesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ws.query.moderationjournal", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebClientGIBDD.ModerationJournalQueryService.CancelledLicensesFilter filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ws.query.moderationjournal", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger")]
        public string pageNumber;
        
        public getCancelledLicensesRequest() {
        }
        
        public getCancelledLicensesRequest(WebClientGIBDD.ModerationJournalQueryService.CancelledLicensesFilter filter, string pageNumber) {
            this.filter = filter;
            this.pageNumber = pageNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="queryCancelledLicensesResponse", WrapperNamespace="urn:ws.query.moderationjournal", IsWrapped=true)]
    public partial class getCancelledLicensesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ws.query.moderationjournal", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebClientGIBDD.ModerationJournalQueryService.ResponseStatusType status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ws.query.moderationjournal", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string statusComment;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ws.query.moderationjournal", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool hasMoreRecords;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ws.query.moderationjournal", Order=3)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("license", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public WebClientGIBDD.ModerationJournalQueryService.ResponseLicense[] licenses;
        
        public getCancelledLicensesResponse() {
        }
        
        public getCancelledLicensesResponse(WebClientGIBDD.ModerationJournalQueryService.ResponseStatusType status, string statusComment, bool hasMoreRecords, WebClientGIBDD.ModerationJournalQueryService.ResponseLicense[] licenses) {
            this.status = status;
            this.statusComment = statusComment;
            this.hasMoreRecords = hasMoreRecords;
            this.licenses = licenses;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ModerationJournalQueryServiceChannel : WebClientGIBDD.ModerationJournalQueryService.ModerationJournalQueryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ModerationJournalQueryServiceClient : System.ServiceModel.ClientBase<WebClientGIBDD.ModerationJournalQueryService.ModerationJournalQueryService>, WebClientGIBDD.ModerationJournalQueryService.ModerationJournalQueryService {
        
        public ModerationJournalQueryServiceClient() {
        }
        
        public ModerationJournalQueryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ModerationJournalQueryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModerationJournalQueryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModerationJournalQueryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebClientGIBDD.ModerationJournalQueryService.getCancelledLicensesResponse WebClientGIBDD.ModerationJournalQueryService.ModerationJournalQueryService.getCancelledLicenses(WebClientGIBDD.ModerationJournalQueryService.getCancelledLicensesRequest request) {
            return base.Channel.getCancelledLicenses(request);
        }
        
        public WebClientGIBDD.ModerationJournalQueryService.ResponseStatusType getCancelledLicenses(WebClientGIBDD.ModerationJournalQueryService.CancelledLicensesFilter filter, string pageNumber, out string statusComment, out bool hasMoreRecords, out WebClientGIBDD.ModerationJournalQueryService.ResponseLicense[] licenses) {
            WebClientGIBDD.ModerationJournalQueryService.getCancelledLicensesRequest inValue = new WebClientGIBDD.ModerationJournalQueryService.getCancelledLicensesRequest();
            inValue.filter = filter;
            inValue.pageNumber = pageNumber;
            WebClientGIBDD.ModerationJournalQueryService.getCancelledLicensesResponse retVal = ((WebClientGIBDD.ModerationJournalQueryService.ModerationJournalQueryService)(this)).getCancelledLicenses(inValue);
            statusComment = retVal.statusComment;
            hasMoreRecords = retVal.hasMoreRecords;
            licenses = retVal.licenses;
            return retVal.status;
        }
    }
}
