CREATE PROCEDURE [dbo].[InsertTMRecordForXMLBody] @TARGETTABLESCHEMA NVARCHAR(255),
	@TARGETTABLENAME NVARCHAR(255),
	@VALUES tt_KeyValueMap READONLY,
	@SOURCEXQUERY NVARCHAR(MAX),
	@XMLBODY XML,
	@RECORDID INT OUTPUT
AS
DECLARE @MESSAGEID VARCHAR(36);
DECLARE @LOCAL_VALUES tt_KeyValueMap;

SET @MESSAGEID = [dbo].[fn_GetCoordinateV5RequestMessageId](@XMLBODY);

INSERT INTO @LOCAL_VALUES
SELECT *
FROM @VALUES;

IF EXISTS (
		SELECT [KEY]
		FROM @LOCAL_VALUES
		WHERE [KEY] = N'MessageId'
		)
	UPDATE @LOCAL_VALUES
	SET [VALUE_STR] = @MESSAGEID
	WHERE [KEY] = N'MessageId';
ELSE
	INSERT INTO @LOCAL_VALUES (
		[KEY],
		[VALUE_STR]
		)
	VALUES (
		N'MessageId',
		@MESSAGEID
		);

EXEC [dbo].[InsertRecordForXMLBody] @TARGETTABLESCHEMA,
	@TARGETTABLENAME,
	@LOCAL_VALUES,
	@SOURCEXQUERY,
	@XMLBODY,
	@RECORDID OUTPUT;

RETURN 0
