CREATE PROCEDURE [dbo].[InsertRecordForXMLBody] @TARGETTABLESCHEMA NVARCHAR(255),
	@TARGETTABLENAME NVARCHAR(255),
	@VALUES TT_KEYVALUEMAP READONLY,
	@SOURCEXQUERY NVARCHAR(MAX),
	@XMLBODY XML,
	@RECORDID INT OUTPUT
AS
DECLARE @EXEC_SQL NVARCHAR(MAX);

SET @RECORDID = NULL;
SET @EXEC_SQL = [dbo].[fn_BuildInsertStatementForXMLBody](@TARGETTABLESCHEMA, @TARGETTABLENAME, @VALUES, @SOURCEXQUERY, N'XMLBODY', N'ID_OUT');

IF @EXEC_SQL IS NULL
	OR @EXEC_SQL = ''
	RAISERROR ('Empty insert SQL statement generated', 18, 1);
ELSE
BEGIN TRY
	EXEC [dbo].[sp_executesql] @STATEMENT = @EXEC_SQL,
		@PARAMS = N'@XMLBODY XML, @ID_OUT INT OUTPUT',
		@XMLBODY = @XMLBODY,
		@ID_OUT = @RECORDID OUTPUT;
END TRY

BEGIN CATCH
	DECLARE @ERR_MESSAGE NVARCHAR(4000);
	DECLARE @ERR_SEVERITY INT;

	SELECT @ERR_MESSAGE = ERROR_MESSAGE(),
		@ERR_SEVERITY = ERROR_SEVERITY();
	-- IN ORDER TO BE ABLE TO CATCH PROCEDURE NAME IF EXCEPTION OCCURED INSIDE DYNAMIC SQL STATEMENT
	RAISERROR (@ERR_MESSAGE, @ERR_SEVERITY, 1);
END CATCH

RETURN 0