CREATE PROCEDURE [dbo].[InsertRequestAccountForXMLBody]
	@SOURCEXQUERY NVARCHAR(MAX),
	@XMLBODY XML,
	@RECORDID INT OUTPUT
AS
	DECLARE @VALUES tt_KeyValueMap;
	DECLARE @POSTALADDRESS_ID INT;
	DECLARE @POSTALADDRESS_XQUERY NVARCHAR(MAX);
	DECLARE @FACTADDRESS_ID INT;
	DECLARE @FACTADDRESS_XQUERY NVARCHAR(MAX);
	DECLARE @ORGHEAD_ID INT;
	DECLARE @ORGHEAD_XQUERY NVARCHAR(MAX);

	SET @POSTALADDRESS_XQUERY = CONCAT(@SOURCEXQUERY, N'/PostalAddress');
	SET @FACTADDRESS_XQUERY = CONCAT(@SOURCEXQUERY, N'/FactAddress');
	SET @ORGHEAD_XQUERY = CONCAT(@SOURCEXQUERY, N'/OrgHead');
	SET @RECORDID = NULL;

	-- ПОЧТОВЫЙ АДРЕС
	EXEC [dbo].[InsertAddressForXMLBody] N'PostalAddress', @POSTALADDRESS_XQUERY, @XMLBODY, @POSTALADDRESS_ID OUTPUT;
	-- ФАКТИЧЕСКИЙ АДРЕС
	EXEC [dbo].[InsertAddressForXMLBody] N'FactAddress', @FACTADDRESS_XQUERY, @XMLBODY, @FACTADDRESS_ID OUTPUT;
	-- ГЛАВА ЮРИДИЧЕСКОГО ЛИЦА
	EXEC [dbo].[InsertRequestContactForXMLBody] @ORGHEAD_XQUERY, @XMLBODY, @ORGHEAD_ID OUTPUT;

	INSERT INTO @VALUES ([KEY], [VALUE_INT]) VALUES (N'PostalAddress', @POSTALADDRESS_ID);
	INSERT INTO @VALUES ([KEY], [VALUE_INT]) VALUES (N'FactAddress', @FACTADDRESS_ID);
	INSERT INTO @VALUES ([KEY], [VALUE_INT]) VALUES (N'RequestContact', @ORGHEAD_ID);
	EXEC [dbo].[InsertTMRecordForXMLBody] N'DBO', N'REQUESTACCOUNT', @VALUES, @SOURCEXQUERY, @XMLBODY, @RECORDID OUTPUT;
RETURN 0
