CREATE PROCEDURE [dbo].[InsertAddressForXMLBody]
	@TYPE NVARCHAR(255),
	@SOURCEXQUERY NVARCHAR(MAX),
	@XMLBODY XML,
	@RECORDID INT OUTPUT
AS
	DECLARE @VALUES tt_KeyValueMap;

	SET @RECORDID = NULL;
	INSERT INTO @VALUES ([KEY], [VALUE_STR]) VALUES (N'Type', @TYPE);

	EXEC [dbo].[InsertTMRecordForXMLBody] N'DBO', N'ADDRESS', @VALUES, @SOURCEXQUERY, @XMLBODY, @RECORDID OUTPUT;
RETURN 0
