CREATE PROCEDURE [dbo].[InsertServicePropertiesForXMLBody]
	@SOURCEXQUERY NVARCHAR(MAX),
	@XMLBODY XML,
	@RECORDID INT OUTPUT
AS
	DECLARE @VALUES tt_KeyValueMap;
	DECLARE @SERVICE_PROPS_ID INT;
	DECLARE @LAST_TAXI_ID INT;
	DECLARE @TAXILIST_XQUERY NVARCHAR(MAX);

	SET @RECORDID = NULL;
	SET @SERVICE_PROPS_ID = NULL;
	SET @LAST_TAXI_ID = NULL;
	SET @TAXILIST_XQUERY = CONCAT(@SOURCEXQUERY, N'/taxi_infolist/taxi_info');

	-- ЗАПИСЬ АТТРИБУТОВ УСЛУГИ ТАКСИ
	EXEC [dbo].[InsertTMRecordForXMLBody] N'DBO', N'SERVICEPROPERTIES', @VALUES, @SOURCEXQUERY, @XMLBODY, @SERVICE_PROPS_ID OUTPUT;

	-- ВСЕ АВТОМАШИНЫ ЗАЯВКИ
	INSERT INTO @VALUES([KEY], [VALUE_INT]) VALUES(N'ServiceProperties', @SERVICE_PROPS_ID);
	EXEC [dbo].[InsertTMRecordForXMLBody] N'DBO', N'TAXI_INFO', @VALUES, @TAXILIST_XQUERY, @XMLBODY, @LAST_TAXI_ID OUTPUT;

	SET @RECORDID = @SERVICE_PROPS_ID;
RETURN 0
