CREATE PROCEDURE [dbo].[InsertAddressForXMLBody]
	@TYPE NVARCHAR(255),
	@SOURCEXQUERY NVARCHAR(MAX),
	@XMLBODY XML,
	@RECORDID INT OUTPUT
AS
	DECLARE @MESSAGEID VARCHAR(36);
	DECLARE @VALUES TT_KEYVALUEMAP;

	SET @MESSAGEID = [dbo].[fn_GetCoordinateV5RequestMessageId] (@XMLBODY);
	SET @RECORDID = NULL;
	INSERT INTO @VALUES ([KEY], [VALUE_STR]) VALUES (N'MessageId', @MESSAGEID);
	INSERT INTO @VALUES ([KEY], [VALUE_STR]) VALUES (N'Type', @TYPE);

	EXEC [dbo].[InsertRecordForXMLBody] N'DBO', N'ADDRESS', @VALUES, @SOURCEXQUERY, @XMLBODY, @RECORDID OUTPUT;
RETURN 0
