//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18449
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClientGIBDD.SpecialTransportDataReceiverService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ws.receiver.specialtransport")]
    public partial class RuntimeExceptionType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string exceptionCodeField;
        
        private string exceptionInfoField;
        
        private string exceptionDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ExceptionCode {
            get {
                return this.exceptionCodeField;
            }
            set {
                this.exceptionCodeField = value;
                this.RaisePropertyChanged("ExceptionCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ExceptionInfo {
            get {
                return this.exceptionInfoField;
            }
            set {
                this.exceptionInfoField = value;
                this.RaisePropertyChanged("ExceptionInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ExceptionData {
            get {
                return this.exceptionDataField;
            }
            set {
                this.exceptionDataField = value;
                this.RaisePropertyChanged("ExceptionData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ws.receiver.specialtransport")]
    public partial class recordStatusType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string recordIdField;
        
        private RecordStatusCodeType recordStatusCodeField;
        
        private string recordStatusTextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string RecordId {
            get {
                return this.recordIdField;
            }
            set {
                this.recordIdField = value;
                this.RaisePropertyChanged("RecordId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public RecordStatusCodeType RecordStatusCode {
            get {
                return this.recordStatusCodeField;
            }
            set {
                this.recordStatusCodeField = value;
                this.RaisePropertyChanged("RecordStatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string RecordStatusText {
            get {
                return this.recordStatusTextField;
            }
            set {
                this.recordStatusTextField = value;
                this.RaisePropertyChanged("RecordStatusText");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ws.receiver.specialtransport")]
    public enum RecordStatusCodeType {
        
        /// <remarks/>
        INSERTED,
        
        /// <remarks/>
        UPDATED,
        
        /// <remarks/>
        FAILED,
        
        /// <remarks/>
        IGNORED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ws.receiver.specialtransport")]
    public partial class RecordsStatusesType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private recordStatusType[] recordStatusField;
        
        private int sizeField;
        
        private int loadedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RecordStatus", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public recordStatusType[] RecordStatus {
            get {
                return this.recordStatusField;
            }
            set {
                this.recordStatusField = value;
                this.RaisePropertyChanged("RecordStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
                this.RaisePropertyChanged("size");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int loaded {
            get {
                return this.loadedField;
            }
            set {
                this.loadedField = value;
                this.RaisePropertyChanged("loaded");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ws.receiver.specialtransport")]
    public partial class DataPackageInfoType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string packageIdField;
        
        private ProccessingStageCodeType proccessingStageCodeField;
        
        private System.DateTime processingStageDateField;
        
        private string processingStageInfoField;
        
        private RecordsStatusesType recordsStatusesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PackageId {
            get {
                return this.packageIdField;
            }
            set {
                this.packageIdField = value;
                this.RaisePropertyChanged("PackageId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ProccessingStageCodeType ProccessingStageCode {
            get {
                return this.proccessingStageCodeField;
            }
            set {
                this.proccessingStageCodeField = value;
                this.RaisePropertyChanged("ProccessingStageCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime ProcessingStageDate {
            get {
                return this.processingStageDateField;
            }
            set {
                this.processingStageDateField = value;
                this.RaisePropertyChanged("ProcessingStageDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ProcessingStageInfo {
            get {
                return this.processingStageInfoField;
            }
            set {
                this.processingStageInfoField = value;
                this.RaisePropertyChanged("ProcessingStageInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public RecordsStatusesType RecordsStatuses {
            get {
                return this.recordsStatusesField;
            }
            set {
                this.recordsStatusesField = value;
                this.RaisePropertyChanged("RecordsStatuses");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ws.receiver.specialtransport")]
    public enum ProccessingStageCodeType {
        
        /// <remarks/>
        NOTEXIST,
        
        /// <remarks/>
        CREATED,
        
        /// <remarks/>
        VALIDATED,
        
        /// <remarks/>
        INVALIDATED,
        
        /// <remarks/>
        QUEUED,
        
        /// <remarks/>
        PROCESSING,
        
        /// <remarks/>
        LOADED,
        
        /// <remarks/>
        FAILED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ws.receiver.specialtransport")]
    public partial class OrganizationType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string organizationTitleField;
        
        private string organizationAddressField;
        
        private string organizationPhoneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string OrganizationTitle {
            get {
                return this.organizationTitleField;
            }
            set {
                this.organizationTitleField = value;
                this.RaisePropertyChanged("OrganizationTitle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string OrganizationAddress {
            get {
                return this.organizationAddressField;
            }
            set {
                this.organizationAddressField = value;
                this.RaisePropertyChanged("OrganizationAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string OrganizationPhone {
            get {
                return this.organizationPhoneField;
            }
            set {
                this.organizationPhoneField = value;
                this.RaisePropertyChanged("OrganizationPhone");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ws.receiver.specialtransport")]
    public partial class VehicleType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vehicleRegNumberField;
        
        private string vehicleType1Field;
        
        private string vehicleBrandField;
        
        private string vehicleModelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string VehicleRegNumber {
            get {
                return this.vehicleRegNumberField;
            }
            set {
                this.vehicleRegNumberField = value;
                this.RaisePropertyChanged("VehicleRegNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VehicleType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string VehicleType1 {
            get {
                return this.vehicleType1Field;
            }
            set {
                this.vehicleType1Field = value;
                this.RaisePropertyChanged("VehicleType1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string VehicleBrand {
            get {
                return this.vehicleBrandField;
            }
            set {
                this.vehicleBrandField = value;
                this.RaisePropertyChanged("VehicleBrand");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string VehicleModel {
            get {
                return this.vehicleModelField;
            }
            set {
                this.vehicleModelField = value;
                this.RaisePropertyChanged("VehicleModel");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ws.receiver.specialtransport")]
    public partial class RecordType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string recordIdField;
        
        private System.DateTime agreementDateField;
        
        private System.DateTime permitStartDateField;
        
        private System.DateTime permitEndDateField;
        
        private long categoryCodeField;
        
        private long restrictionAreaCodeField;
        
        private string causeInclusionField;
        
        private VehicleType vehicleField;
        
        private OrganizationType organizationField;
        
        private string catalogNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string RecordId {
            get {
                return this.recordIdField;
            }
            set {
                this.recordIdField = value;
                this.RaisePropertyChanged("RecordId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=1)]
        public System.DateTime AgreementDate {
            get {
                return this.agreementDateField;
            }
            set {
                this.agreementDateField = value;
                this.RaisePropertyChanged("AgreementDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime PermitStartDate {
            get {
                return this.permitStartDateField;
            }
            set {
                this.permitStartDateField = value;
                this.RaisePropertyChanged("PermitStartDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime PermitEndDate {
            get {
                return this.permitEndDateField;
            }
            set {
                this.permitEndDateField = value;
                this.RaisePropertyChanged("PermitEndDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public long CategoryCode {
            get {
                return this.categoryCodeField;
            }
            set {
                this.categoryCodeField = value;
                this.RaisePropertyChanged("CategoryCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public long RestrictionAreaCode {
            get {
                return this.restrictionAreaCodeField;
            }
            set {
                this.restrictionAreaCodeField = value;
                this.RaisePropertyChanged("RestrictionAreaCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string CauseInclusion {
            get {
                return this.causeInclusionField;
            }
            set {
                this.causeInclusionField = value;
                this.RaisePropertyChanged("CauseInclusion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public VehicleType Vehicle {
            get {
                return this.vehicleField;
            }
            set {
                this.vehicleField = value;
                this.RaisePropertyChanged("Vehicle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public OrganizationType Organization {
            get {
                return this.organizationField;
            }
            set {
                this.organizationField = value;
                this.RaisePropertyChanged("Organization");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string CatalogNumber {
            get {
                return this.catalogNumberField;
            }
            set {
                this.catalogNumberField = value;
                this.RaisePropertyChanged("CatalogNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ws.receiver.specialtransport")]
    public partial class RecordsType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RecordType[] recordField;
        
        private int sizeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Record", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public RecordType[] Record {
            get {
                return this.recordField;
            }
            set {
                this.recordField = value;
                this.RaisePropertyChanged("Record");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
                this.RaisePropertyChanged("size");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ws.receiver.specialtransport")]
    public partial class DataPackageType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string packageIdField;
        
        private System.DateTime packageCreatedDateField;
        
        private RecordsType recordsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PackageId {
            get {
                return this.packageIdField;
            }
            set {
                this.packageIdField = value;
                this.RaisePropertyChanged("PackageId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime PackageCreatedDate {
            get {
                return this.packageCreatedDateField;
            }
            set {
                this.packageCreatedDateField = value;
                this.RaisePropertyChanged("PackageCreatedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public RecordsType Records {
            get {
                return this.recordsField;
            }
            set {
                this.recordsField = value;
                this.RaisePropertyChanged("Records");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ws.receiver.specialtransport")]
    public partial class DataPackagesType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DataPackageType[] dataPackageField;
        
        private string ownerField;
        
        private int sizeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DataPackage", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public DataPackageType[] DataPackage {
            get {
                return this.dataPackageField;
            }
            set {
                this.dataPackageField = value;
                this.RaisePropertyChanged("DataPackage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
                this.RaisePropertyChanged("owner");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
                this.RaisePropertyChanged("size");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:ws.receiver.specialtransport", ConfigurationName="SpecialTransportDataReceiverService.SpecialTransportDataReceiverService")]
    public interface SpecialTransportDataReceiverService {
        
        // CODEGEN: Контракт генерации сообщений с операцией putDataPackages не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="urn:ws.receiver.specialtransport:SpecialTransportDataReceiverService:putDataPacka" +
            "gesRequest", ReplyAction="urn:ws.receiver.specialtransport:SpecialTransportDataReceiverService:putDataPacka" +
            "gesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebClientGIBDD.SpecialTransportDataReceiverService.RuntimeExceptionType), Action="http://www.w3.org/2005/08/addressing/soap/fault", Name="RuntimeException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebClientGIBDD.SpecialTransportDataReceiverService.putDataPackagesResponse putDataPackages(WebClientGIBDD.SpecialTransportDataReceiverService.putDataPackagesRequest request);
        
        // CODEGEN: Контракт генерации сообщений с операцией getDataPackagesInfo не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="urn:ws.receiver.specialtransport:SpecialTransportDataReceiverService:getDataPacka" +
            "gesInfoRequest", ReplyAction="urn:ws.receiver.specialtransport:SpecialTransportDataReceiverService:getDataPacka" +
            "gesInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebClientGIBDD.SpecialTransportDataReceiverService.RuntimeExceptionType), Action="http://www.w3.org/2005/08/addressing/soap/fault", Name="RuntimeException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebClientGIBDD.SpecialTransportDataReceiverService.getDataPackagesInfoResponse getDataPackagesInfo(WebClientGIBDD.SpecialTransportDataReceiverService.getDataPackagesInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class putDataPackagesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ws.receiver.specialtransport", Order=0)]
        public WebClientGIBDD.SpecialTransportDataReceiverService.DataPackagesType DataPackages;
        
        public putDataPackagesRequest() {
        }
        
        public putDataPackagesRequest(WebClientGIBDD.SpecialTransportDataReceiverService.DataPackagesType DataPackages) {
            this.DataPackages = DataPackages;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class putDataPackagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ws.receiver.specialtransport", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DataPackageInfo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public WebClientGIBDD.SpecialTransportDataReceiverService.DataPackageInfoType[] DataPackagesInfo;
        
        public putDataPackagesResponse() {
        }
        
        public putDataPackagesResponse(WebClientGIBDD.SpecialTransportDataReceiverService.DataPackageInfoType[] DataPackagesInfo) {
            this.DataPackagesInfo = DataPackagesInfo;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ws.receiver.specialtransport")]
    public partial class DataPackagesInfoRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] packageIdField;
        
        private string ownerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PackageId", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string[] PackageId {
            get {
                return this.packageIdField;
            }
            set {
                this.packageIdField = value;
                this.RaisePropertyChanged("PackageId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
                this.RaisePropertyChanged("owner");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDataPackagesInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ws.receiver.specialtransport", Order=0)]
        public WebClientGIBDD.SpecialTransportDataReceiverService.DataPackagesInfoRequestType DataPackagesInfoRequest;
        
        public getDataPackagesInfoRequest() {
        }
        
        public getDataPackagesInfoRequest(WebClientGIBDD.SpecialTransportDataReceiverService.DataPackagesInfoRequestType DataPackagesInfoRequest) {
            this.DataPackagesInfoRequest = DataPackagesInfoRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDataPackagesInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ws.receiver.specialtransport", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DataPackageInfo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public WebClientGIBDD.SpecialTransportDataReceiverService.DataPackageInfoType[] DataPackagesInfo;
        
        public getDataPackagesInfoResponse() {
        }
        
        public getDataPackagesInfoResponse(WebClientGIBDD.SpecialTransportDataReceiverService.DataPackageInfoType[] DataPackagesInfo) {
            this.DataPackagesInfo = DataPackagesInfo;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SpecialTransportDataReceiverServiceChannel : WebClientGIBDD.SpecialTransportDataReceiverService.SpecialTransportDataReceiverService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SpecialTransportDataReceiverServiceClient : System.ServiceModel.ClientBase<WebClientGIBDD.SpecialTransportDataReceiverService.SpecialTransportDataReceiverService>, WebClientGIBDD.SpecialTransportDataReceiverService.SpecialTransportDataReceiverService {
        
        public SpecialTransportDataReceiverServiceClient() {
        }
        
        public SpecialTransportDataReceiverServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SpecialTransportDataReceiverServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SpecialTransportDataReceiverServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SpecialTransportDataReceiverServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebClientGIBDD.SpecialTransportDataReceiverService.putDataPackagesResponse WebClientGIBDD.SpecialTransportDataReceiverService.SpecialTransportDataReceiverService.putDataPackages(WebClientGIBDD.SpecialTransportDataReceiverService.putDataPackagesRequest request) {
            return base.Channel.putDataPackages(request);
        }
        
        public WebClientGIBDD.SpecialTransportDataReceiverService.DataPackageInfoType[] putDataPackages(WebClientGIBDD.SpecialTransportDataReceiverService.DataPackagesType DataPackages) {
            WebClientGIBDD.SpecialTransportDataReceiverService.putDataPackagesRequest inValue = new WebClientGIBDD.SpecialTransportDataReceiverService.putDataPackagesRequest();
            inValue.DataPackages = DataPackages;
            WebClientGIBDD.SpecialTransportDataReceiverService.putDataPackagesResponse retVal = ((WebClientGIBDD.SpecialTransportDataReceiverService.SpecialTransportDataReceiverService)(this)).putDataPackages(inValue);
            return retVal.DataPackagesInfo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebClientGIBDD.SpecialTransportDataReceiverService.getDataPackagesInfoResponse WebClientGIBDD.SpecialTransportDataReceiverService.SpecialTransportDataReceiverService.getDataPackagesInfo(WebClientGIBDD.SpecialTransportDataReceiverService.getDataPackagesInfoRequest request) {
            return base.Channel.getDataPackagesInfo(request);
        }
        
        public WebClientGIBDD.SpecialTransportDataReceiverService.DataPackageInfoType[] getDataPackagesInfo(WebClientGIBDD.SpecialTransportDataReceiverService.DataPackagesInfoRequestType DataPackagesInfoRequest) {
            WebClientGIBDD.SpecialTransportDataReceiverService.getDataPackagesInfoRequest inValue = new WebClientGIBDD.SpecialTransportDataReceiverService.getDataPackagesInfoRequest();
            inValue.DataPackagesInfoRequest = DataPackagesInfoRequest;
            WebClientGIBDD.SpecialTransportDataReceiverService.getDataPackagesInfoResponse retVal = ((WebClientGIBDD.SpecialTransportDataReceiverService.SpecialTransportDataReceiverService)(this)).getDataPackagesInfo(inValue);
            return retVal.DataPackagesInfo;
        }
    }
}
