#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TM.DatabaseModel
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TM.Data")]
	public partial class TM_DatabaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertIncomingRequestXML(IncomingRequestXML instance);
    partial void UpdateIncomingRequestXML(IncomingRequestXML instance);
    partial void DeleteIncomingRequestXML(IncomingRequestXML instance);
    #endregion
		
		public TM_DatabaseDataContext() : 
				base(global::TM.DatabaseModel.Properties.Settings.Default.TM_DataConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TM_DatabaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TM_DatabaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TM_DatabaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TM_DatabaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<IncomingRequestXML> IncomingRequestXMLs
		{
			get
			{
				return this.GetTable<IncomingRequestXML>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IncomingRequestXML")]
	public partial class IncomingRequestXML : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Xml.Linq.XElement _RequestBody;
		
		private System.DateTime _InDate;
		
		private string _Source;
		
		private System.Nullable<System.DateTime> _OutDate;
		
		private System.Nullable<System.DateTime> _ProcessLastAttemptDate;
		
		private System.Nullable<bool> _Processed;
		
		private string _BodyMessageId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnRequestBodyChanging(System.Xml.Linq.XElement value);
    partial void OnRequestBodyChanged();
    partial void OnInDateChanging(System.DateTime value);
    partial void OnInDateChanged();
    partial void OnSourceChanging(string value);
    partial void OnSourceChanged();
    partial void OnOutDateChanging(System.Nullable<System.DateTime> value);
    partial void OnOutDateChanged();
    partial void OnProcessLastAttemptDateChanging(System.Nullable<System.DateTime> value);
    partial void OnProcessLastAttemptDateChanged();
    partial void OnProcessedChanging(System.Nullable<bool> value);
    partial void OnProcessedChanged();
    partial void OnBodyMessageIdChanging(string value);
    partial void OnBodyMessageIdChanged();
    #endregion
		
		public IncomingRequestXML()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestBody", DbType="Xml NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Xml.Linq.XElement RequestBody
		{
			get
			{
				return this._RequestBody;
			}
			set
			{
				if ((this._RequestBody != value))
				{
					this.OnRequestBodyChanging(value);
					this.SendPropertyChanging();
					this._RequestBody = value;
					this.SendPropertyChanged("RequestBody");
					this.OnRequestBodyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InDate", DbType="DateTime NOT NULL")]
		public System.DateTime InDate
		{
			get
			{
				return this._InDate;
			}
			set
			{
				if ((this._InDate != value))
				{
					this.OnInDateChanging(value);
					this.SendPropertyChanging();
					this._InDate = value;
					this.SendPropertyChanged("InDate");
					this.OnInDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Source", DbType="NVarChar(50)")]
		public string Source
		{
			get
			{
				return this._Source;
			}
			set
			{
				if ((this._Source != value))
				{
					this.OnSourceChanging(value);
					this.SendPropertyChanging();
					this._Source = value;
					this.SendPropertyChanged("Source");
					this.OnSourceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OutDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> OutDate
		{
			get
			{
				return this._OutDate;
			}
			set
			{
				if ((this._OutDate != value))
				{
					this.OnOutDateChanging(value);
					this.SendPropertyChanging();
					this._OutDate = value;
					this.SendPropertyChanged("OutDate");
					this.OnOutDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProcessLastAttemptDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ProcessLastAttemptDate
		{
			get
			{
				return this._ProcessLastAttemptDate;
			}
			set
			{
				if ((this._ProcessLastAttemptDate != value))
				{
					this.OnProcessLastAttemptDateChanging(value);
					this.SendPropertyChanging();
					this._ProcessLastAttemptDate = value;
					this.SendPropertyChanged("ProcessLastAttemptDate");
					this.OnProcessLastAttemptDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Processed", AutoSync=AutoSync.Always, DbType="Bit", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<bool> Processed
		{
			get
			{
				return this._Processed;
			}
			set
			{
				if ((this._Processed != value))
				{
					this.OnProcessedChanging(value);
					this.SendPropertyChanging();
					this._Processed = value;
					this.SendPropertyChanged("Processed");
					this.OnProcessedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BodyMessageId", AutoSync=AutoSync.Always, DbType="VarChar(36)", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public string BodyMessageId
		{
			get
			{
				return this._BodyMessageId;
			}
			set
			{
				if ((this._BodyMessageId != value))
				{
					this.OnBodyMessageIdChanging(value);
					this.SendPropertyChanging();
					this._BodyMessageId = value;
					this.SendPropertyChanged("BodyMessageId");
					this.OnBodyMessageIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
