//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TM.SP.AppPages.Validators {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringsRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TM.SP.AppPages.Validators.StringsRes", typeof(StringsRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cуществуют действующие разрешения.
        /// </summary>
        internal static string actingLicensesError {
            get {
                return ResourceManager.GetString("actingLicensesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аннулирование.
        /// </summary>
        internal static string ctCancellation {
            get {
                return ResourceManager.GetString("ctCancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выдача дубликата.
        /// </summary>
        internal static string ctDuplicate {
            get {
                return ResourceManager.GetString("ctDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новое.
        /// </summary>
        internal static string ctNew {
            get {
                return ResourceManager.GetString("ctNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переоформление.
        /// </summary>
        internal static string ctRenew {
            get {
                return ResourceManager.GetString("ctRenew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разрешение аннулировано.
        /// </summary>
        internal static string licenseCancelledErr {
            get {
                return ResourceManager.GetString("licenseCancelledErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аннулировано.
        /// </summary>
        internal static string LicenseStatusCancellation {
            get {
                return ResourceManager.GetString("LicenseStatusCancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствует действующее разрешение для аннулирования.
        /// </summary>
        internal static string noActingLicenseForCancellationErr {
            get {
                return ResourceManager.GetString("noActingLicenseForCancellationErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствует действующее разрешение для выдачи дубликата.
        /// </summary>
        internal static string noActingLicenseForDuplicateErr {
            get {
                return ResourceManager.GetString("noActingLicenseForDuplicateErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствует действующее разрешение для переоформления.
        /// </summary>
        internal static string noActingLicenseForRenewErr {
            get {
                return ResourceManager.GetString("noActingLicenseForRenewErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В обращении не указан заявитель или у заявителя не указан ОГРН.
        /// </summary>
        internal static string noDeclarantOgrnErr {
            get {
                return ResourceManager.GetString("noDeclarantOgrnErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указан номер ранее выданного разрешения.
        /// </summary>
        internal static string noPrevLicNumberErr {
            get {
                return ResourceManager.GetString("noPrevLicNumberErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОГРН заявителя не совпадает с данными из разрешения.
        /// </summary>
        internal static string ogrnMismatchErr {
            get {
                return ResourceManager.GetString("ogrnMismatchErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В другом обращении имеется ТС со статусом &quot;Решено положительно&quot;, по которому не завершена работа.
        /// </summary>
        internal static string requestExistsForAny {
            get {
                return ResourceManager.GetString("requestExistsForAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В рассмотрении находится обращение по аннулированию разрешения по ТС.
        /// </summary>
        internal static string requestExistsForCancellation {
            get {
                return ResourceManager.GetString("requestExistsForCancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В рассмотрении находится обращение на выдачу дубликата разрешения по ТС.
        /// </summary>
        internal static string requestExistsForDuplicate {
            get {
                return ResourceManager.GetString("requestExistsForDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В рассмотрении находится обращение на выдачу нового разрешения по ТС.
        /// </summary>
        internal static string requestExistsForNew {
            get {
                return ResourceManager.GetString("requestExistsForNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В рассмотрении находится обращение на переоформление разрешения по ТС.
        /// </summary>
        internal static string requestExistsForRenew {
            get {
                return ResourceManager.GetString("requestExistsForRenew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гос. номер ТС не совпадает с данными из разрешения.
        /// </summary>
        internal static string stateNumMismatchErr {
            get {
                return ResourceManager.GetString("stateNumMismatchErr", resourceCulture);
            }
        }
    }
}
